### ISSUE TITLE
Add support to x14

### ISSUE THREAD

**Issue by Nasreddine** [rsm-gh/akbl#114]
# System information

+ Distribution name: Ubuntu 
+ Distribution version: 22.10
+ Python3 version: 3.10.7
+ akbl version: 2019.05.26

+ Computer model:
+ Daemon status: False

# Bug description

When running setup script, I'm getting this exception : 

*********************************** 
 *** Installing AKBL v2019.05.26 *** 
 *********************************** 

[1/5] Removing previous versions..

Disabling the systemd daemon...
Removed "/etc/systemd/system/basic.target.wants/akbl.service".

Removing the software links..
python3 directory removed
python3.10 link removed
python3.11 link removed

Removing the software files and directories..
removed.f: /usr/share/applications/AKBL.desktop
removed.f: /usr/bin/akbl
removed.d: /usr/share/AKBL
removed.d: /usr/share/doc/AKBL
removed.d: /usr/lib/python3/AKBL

[2/5] Installing the software files...
 Copying the software files...
installing: /usr/bin
installing: /usr/share/applications
installing: /usr/share/AKBL
install: omitting directory '/home/nasredine/apps/akbl-stable/usr/share/AKBL/computers'
install: omitting directory '/home/nasredine/apps/akbl-stable/usr/share/AKBL/launch'
install: omitting directory '/home/nasredine/apps/akbl-stable/usr/share/AKBL/test'
installing: /usr/share/AKBL/computers
installing: /usr/share/AKBL/launch
installing: /usr/share/AKBL/test
installing: /usr/share/doc/AKBL
install: omitting directory '/home/nasredine/apps/akbl-stable/usr/share/doc/AKBL/BusData'
install: omitting directory '/home/nasredine/apps/akbl-stable/usr/share/doc/AKBL/ImagesPreview'
install: omitting directory '/home/nasredine/apps/akbl-stable/usr/share/doc/AKBL/Licenses'
install: omitting directory '/home/nasredine/apps/akbl-stable/usr/share/doc/AKBL/Programming'
installing: /usr/share/doc/AKBL/BusData
install: omitting directory '/home/nasredine/apps/akbl-stable/usr/share/doc/AKBL/BusData/Data'
installing: /usr/share/doc/AKBL/BusData/Data
installing: /usr/share/doc/AKBL/ImagesPreview
installing: /usr/share/doc/AKBL/Licenses
installing: /usr/share/doc/AKBL/Programming
install: omitting directory '/home/nasredine/apps/akbl-stable/usr/share/doc/AKBL/Programming/class_diagrams'
installing: /usr/share/doc/AKBL/Programming/class_diagrams
installing: /usr/lib/systemd/system
installing: /usr/lib/python3/AKBL
install: omitting directory '/home/nasredine/apps/akbl-stable/usr/lib/python3/AKBL/Addons'
install: omitting directory '/home/nasredine/apps/akbl-stable/usr/lib/python3/AKBL/Data'
install: omitting directory '/home/nasredine/apps/akbl-stable/usr/lib/python3/AKBL/Engine'
installing: /usr/lib/python3/AKBL/Data
install: omitting directory '/home/nasredine/apps/akbl-stable/usr/lib/python3/AKBL/Data/Computer'
install: omitting directory '/home/nasredine/apps/akbl-stable/usr/lib/python3/AKBL/Data/Theme'
installing: /usr/lib/python3/AKBL/Data/Computer
installing: /usr/lib/python3/AKBL/Data/Theme
installing: /usr/lib/python3/AKBL/Engine
installing: /usr/lib/python3/AKBL/Addons
install: omitting directory '/home/nasredine/apps/akbl-stable/usr/lib/python3/AKBL/Addons/BlockTesting'
install: omitting directory '/home/nasredine/apps/akbl-stable/usr/lib/python3/AKBL/Addons/GUI'
install: omitting directory '/home/nasredine/apps/akbl-stable/usr/lib/python3/AKBL/Addons/Indicator'
install: omitting directory '/home/nasredine/apps/akbl-stable/usr/lib/python3/AKBL/Addons/ModelChooser'
installing: /usr/lib/python3/AKBL/Addons/GUI
install: omitting directory '/home/nasredine/apps/akbl-stable/usr/lib/python3/AKBL/Addons/GUI/ColorChooserToolbar'
install: omitting directory '/home/nasredine/apps/akbl-stable/usr/lib/python3/AKBL/Addons/GUI/images'
installing: /usr/lib/python3/AKBL/Addons/GUI/ColorChooserToolbar
installing: /usr/lib/python3/AKBL/Addons/GUI/images
installing: /usr/lib/python3/AKBL/Addons/BlockTesting
installing: /usr/lib/python3/AKBL/Addons/Indicator
install: omitting directory '/home/nasredine/apps/akbl-stable/usr/lib/python3/AKBL/Addons/Indicator/images'
installing: /usr/lib/python3/AKBL/Addons/Indicator/images
installing: /usr/lib/python3/AKBL/Addons/ModelChooser
 Replacing variables...

[3/5] Creating the python links...
linked python3
linked python3.10
linked python3.11

[4/5] Choosing the computer model...
Choose the configuration file from the GTK window that will appear..
Traceback (most recent call last):
  File "/usr/lib/python3.10/AKBL/Engine/Driver.py", line 143, in take_over
    self._device.set_configuration()
  File "/usr/lib/python3/dist-packages/usb/core.py", line 915, in set_configuration
    self._ctx.managed_set_configuration(self, configuration)
  File "/usr/lib/python3/dist-packages/usb/core.py", line 113, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/usb/core.py", line 159, in managed_set_configuration
    self.backend.set_configuration(self.handle, cfg.bConfigurationValue)
  File "/usr/lib/python3/dist-packages/usb/backend/libusb1.py", line 812, in set_configuration
    _check(self.lib.libusb_set_configuration(dev_handle.handle, config_value))
  File "/usr/lib/python3/dist-packages/usb/backend/libusb1.py", line 604, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 2] Entity not found

During handling of the above exception, another exception occurred:

**Traceback (most recent call last):
  File "/usr/share/AKBL/launch/model_chooser.py", line 21, in <module>
    main()
  File "/usr/lib/python3.10/AKBL/Addons/ModelChooser/ModelChooser.py", line 206, in main
    ModelChooser()
  File "/usr/lib/python3.10/AKBL/Addons/ModelChooser/ModelChooser.py", line 93, in __init__
    self.upadte_detected_as()
  File "/usr/lib/python3.10/AKBL/Addons/ModelChooser/ModelChooser.py", line 124, in upadte_detected_as
    driver.find_device()
  File "/usr/lib/python3.10/AKBL/Engine/Driver.py", line 70, in find_device
    self.take_over()
  File "/usr/lib/python3.10/AKBL/Engine/Driver.py", line 145, in take_over
    self._device.detach_kernel_driver(0)
  File "/usr/lib/python3/dist-packages/usb/core.py", line 1121, in detach_kernel_driver
    self._ctx.backend.detach_kernel_driver(
  File "/usr/lib/python3/dist-packages/usb/backend/libusb1.py", line 920, in detach_kernel_driver
    _check(self.lib.libusb_detach_kernel_driver(dev_handle.handle, intf))
  File "/usr/lib/python3/dist-packages/usb/backend/libusb1.py", line 604, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 2] Entity not found**

[5/5] Enabling the daemon...
Created symlink /etc/systemd/system/basic.target.wants/akbl.service → /lib/systemd/system/akbl.service.

 ************************************* 
 *** AKBL v2019.05.26 is installed *** 
 *************************************

**Comment by rsm-gh** [comment]
Hello @Nasreddine ,

I'm sorry but actually this seems to be an USB error, maybe related to Ubuntu or to the USB patch. I will not be able to debug without your computer.

Best regards,
rsm~
