### ISSUE TITLE
Alienware 15 R3 (2016) AW1517 - Alienware Corporation AW1517

### ISSUE THREAD

**Issue by PyroVooDoo** [rsm-gh/akbl#118]
# System information

+ Distribution name: Ubuntu 22.04 
+ Distribution version: Ubuntu 22.04 
+ Python3 version: Python 3.10.12
+ akbl version: 2.dev
+ Computer model: Alienware 15 R3 
+ Daemon status:  True

# Installation Log
```
echu@Alyx:~/Downloads/akbl-stable$ sudo ./setup 
[1/5] Removing previous versions..

 Disabling the systemd daemon...

 Removing the python links..

 Removing the software files and directories..

[2/5] Installing the software files...
installing: /usr/bin
installing: /usr/share/applications
installing: /usr/share/AKBL
install: omitting directory '/home/lechu/Downloads/akbl-stable/usr/share/AKBL/BlockTesting'
install: omitting directory '/home/lechu/Downloads/akbl-stable/usr/share/AKBL/computers'
install: omitting directory '/home/lechu/Downloads/akbl-stable/usr/share/AKBL/GUI'
install: omitting directory '/home/lechu/Downloads/akbl-stable/usr/share/AKBL/Indicator'
install: omitting directory '/home/lechu/Downloads/akbl-stable/usr/share/AKBL/ModelChooser'
install: omitting directory '/home/lechu/Downloads/akbl-stable/usr/share/AKBL/test'
installing: /usr/share/AKBL/test
installing: /usr/share/AKBL/launch
install: cannot stat '/home/lechu/Downloads/akbl-stable/usr/share/AKBL/launch/*': No such file or directory
installing: /usr/share/AKBL/computers
installing: /usr/share/AKBL/GUI
install: omitting directory '/home/lechu/Downloads/akbl-stable/usr/share/AKBL/GUI/ColorChooserToolbar'
install: omitting directory '/home/lechu/Downloads/akbl-stable/usr/share/AKBL/GUI/img'
installing: /usr/share/AKBL/GUI/ColorChooserToolbar
installing: /usr/share/AKBL/GUI/img
installing: /usr/share/AKBL/BlockTesting
installing: /usr/share/AKBL/Indicator
install: omitting directory '/home/lechu/Downloads/akbl-stable/usr/share/AKBL/Indicator/img'
installing: /usr/share/AKBL/Indicator/img
installing: /usr/share/AKBL/ModelChooser
installing: /usr/share/doc/AKBL
install: omitting directory '/home/lechu/Downloads/akbl-stable/usr/share/doc/AKBL/BusData'
install: omitting directory '/home/lechu/Downloads/akbl-stable/usr/share/doc/AKBL/ImagesPreview'
install: omitting directory '/home/lechu/Downloads/akbl-stable/usr/share/doc/AKBL/Licenses'
install: omitting directory '/home/lechu/Downloads/akbl-stable/usr/share/doc/AKBL/Programming'
installing: /usr/share/doc/AKBL/BusData
install: omitting directory '/home/lechu/Downloads/akbl-stable/usr/share/doc/AKBL/BusData/Data'
installing: /usr/share/doc/AKBL/BusData/Data
installing: /usr/share/doc/AKBL/ImagesPreview
installing: /usr/share/doc/AKBL/Licenses
installing: /usr/share/doc/AKBL/Programming
install: omitting directory '/home/lechu/Downloads/akbl-stable/usr/share/doc/AKBL/Programming/class_diagrams'
installing: /usr/share/doc/AKBL/Programming/class_diagrams
installing: /usr/lib/python3/AKBL
install: omitting directory '/home/lechu/Downloads/akbl-stable/usr/lib/python3/AKBL/Computer'
install: omitting directory '/home/lechu/Downloads/akbl-stable/usr/lib/python3/AKBL/Engine'
install: omitting directory '/home/lechu/Downloads/akbl-stable/usr/lib/python3/AKBL/Theme'
installing: /usr/lib/python3/AKBL/Engine
installing: /usr/lib/python3/AKBL/Computer
installing: /usr/lib/python3/AKBL/Theme
installing: /usr/lib/systemd/system

[3/5] Creating the python links...
linked python3.10
linked python3.11

[4/5] Choosing the computer model...
Installed computer set to: Alienware15R3
If you want to change it, use the commands 'akbl --model-chooser-gui' or '--model-chooser-cmd'

[5/5] Enabling the daemon...
Created symlink /etc/systemd/system/basic.target.wants/akbl.service → /lib/systemd/system/akbl.service.

```

# Block Testing Window

Note: To make AKBL work, the Block Testing Window must work. If you're computer is not working with AKBL, start by following this doc:
https://github.com/rsm-gh/akbl#how-to-use-the-block-testing-window

+ Is the block testing working?
No, not working

Hi!!, Thank you very much for all the work, I have a problem with the compatibility of my computer, it uses the AW1517 module.
But I can't find a way to make it work.
The model chooser does not find a compatible model for me, if I do it by CMD, and I use Alienware 15R3 it gives me this error.

Detect USB data>
```
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 004: ID 0bda:58c2 Realtek Semiconductor Corp. Integrated Webcam HD
Bus 001 Device 003: ID 0cf3:e301 Qualcomm Atheros Communications 
Bus 001 Device 002: ID 187c:0530 Alienware Corporation AW1517
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```
 ```
Device: ID 187c:0530 Alienware Corporation AW1517
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               0.02
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x187c Alienware Corporation
  idProduct          0x0530 
  bcdDevice            0.00
  iManufacturer           1 Alienware
  iProduct                2 AW1517
  iSerial                 3 03.00
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x0029
    bNumInterfaces          1
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xe0
      Self Powered
      Remote Wakeup
    MaxPower                0mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      0 
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.01
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      56
          Report Descriptor: (length is 56)
            Item(Global): Usage Page, data= [ 0x00 0xff ] 65280
                            (null)
            Item(Local ): Usage, data= [ 0x01 ] 1
                            (null)
            Item(Main  ): Collection, data= [ 0x01 ] 1
                            Application
            Item(Global): Usage Page, data= [ 0x0c ] 12
                            Consumer
            Item(Local ): Usage, data= [ 0x06 ] 6
                            (null)
            Item(Main  ): Collection, data= [ 0x02 ] 2
                            Logical
            Item(Local ): Usage Minimum, data= [ 0x00 ] 0
                            Unassigned
            Item(Local ): Usage Maximum, data= [ 0x66 ] 102
                            Still
            Item(Global): Logical Minimum, data= [ 0x00 ] 0
            Item(Global): Logical Maximum, data= [ 0x01 ] 1
            Item(Global): Report ID, data= [ 0x01 ] 1
            Item(Global): Report Size, data= [ 0x08 ] 8
            Item(Global): Report Count, data= [ 0x0b ] 11
            Item(Main  ): Input, data= [ 0x02 ] 2
                            Data Variable Absolute No_Wrap Linear
                            Preferred_State No_Null_Position Non_Volatile Bitfield
            Item(Main  ): End Collection, data=none
            Item(Global): Usage Page, data= [ 0x14 ] 20
                            Alphanumeric Display
            Item(Local ): Usage, data= [ 0x2b ] 43
                            Character Report
            Item(Main  ): Collection, data= [ 0x02 ] 2
                            Logical
            Item(Local ): Usage Minimum, data= [ 0x01 ] 1
                            Alphanumeric Display
            Item(Local ): Usage Maximum, data= [ 0x66 ] 102
                            (null)
            Item(Global): Logical Minimum, data= [ 0x00 ] 0
            Item(Global): Logical Maximum, data= [ 0x01 ] 1
            Item(Global): Report ID, data= [ 0x02 ] 2
            Item(Global): Report Size, data= [ 0x08 ] 8
            Item(Global): Report Count, data= [ 0x0b ] 11
            Item(Local ): Usage, data= [ 0x2c ] 44
                            Display Data
            Item(Main  ): Output, data= [ 0x02 ] 2
                            Data Variable Absolute No_Wrap Linear
                            Preferred_State No_Null_Position Non_Volatile Bitfield
            Item(Main  ): End Collection, data=none
            Item(Main  ): End Collection, data=none
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x000a  1x 10 bytes
        bInterval              10
Device Status:     0x0000
  (Bus Powered)
```

```
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 004: ID 0bda:58c2 Realtek Semiconductor Corp. Integrated Webcam HD
Bus 001 Device 003: ID 0cf3:e301 Qualcomm Atheros Communications 
Bus 001 Device 002: ID 187c:0530 Alienware Corporation AW1517
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```

--block-testing
```
Device: ID 187c:0530 Alienware Corporation AW1517
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               0.02
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x187c Alienware Corporation
  idProduct          0x0530 
  bcdDevice            0.00
  iManufacturer           1 Alienware
  iProduct                2 AW1517
  iSerial                 3 03.00
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x0029
    bNumInterfaces          1
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xe0
      Self Powered
      Remote Wakeup
    MaxPower                0mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      0 
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.01
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      56
          Report Descriptor: (length is 56)
            Item(Global): Usage Page, data= [ 0x00 0xff ] 65280
                            (null)
            Item(Local ): Usage, data= [ 0x01 ] 1
                            (null)
            Item(Main  ): Collection, data= [ 0x01 ] 1
                            Application
            Item(Global): Usage Page, data= [ 0x0c ] 12
                            Consumer
            Item(Local ): Usage, data= [ 0x06 ] 6
                            (null)
            Item(Main  ): Collection, data= [ 0x02 ] 2
                            Logical
            Item(Local ): Usage Minimum, data= [ 0x00 ] 0
                            Unassigned
            Item(Local ): Usage Maximum, data= [ 0x66 ] 102
                            Still
            Item(Global): Logical Minimum, data= [ 0x00 ] 0
            Item(Global): Logical Maximum, data= [ 0x01 ] 1
            Item(Global): Report ID, data= [ 0x01 ] 1
            Item(Global): Report Size, data= [ 0x08 ] 8
            Item(Global): Report Count, data= [ 0x0b ] 11
            Item(Main  ): Input, data= [ 0x02 ] 2
                            Data Variable Absolute No_Wrap Linear
                            Preferred_State No_Null_Position Non_Volatile Bitfield
            Item(Main  ): End Collection, data=none
            Item(Global): Usage Page, data= [ 0x14 ] 20
                            Alphanumeric Display
            Item(Local ): Usage, data= [ 0x2b ] 43
                            Character Report
            Item(Main  ): Collection, data= [ 0x02 ] 2
                            Logical
            Item(Local ): Usage Minimum, data= [ 0x01 ] 1
                            Alphanumeric Display
            Item(Local ): Usage Maximum, data= [ 0x66 ] 102
                            (null)
            Item(Global): Logical Minimum, data= [ 0x00 ] 0
            Item(Global): Logical Maximum, data= [ 0x01 ] 1
            Item(Global): Report ID, data= [ 0x02 ] 2
            Item(Global): Report Size, data= [ 0x08 ] 8
            Item(Global): Report Count, data= [ 0x0b ] 11
            Item(Local ): Usage, data= [ 0x2c ] 44
                            Display Data
            Item(Main  ): Output, data= [ 0x02 ] 2
                            Data Variable Absolute No_Wrap Linear
                            Preferred_State No_Null_Position Non_Volatile Bitfield
            Item(Main  ): End Collection, data=none
            Item(Main  ): End Collection, data=none
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x000a  1x 10 bytes
        bInterval              10
Device Status:     0x0000
  (Bus Powered)

ID Vendor: 0x187c
ID Product: 0x0530

BlockTesting.py:10291): dconf-WARNING **: 02:50:16.142: failed to commit changes to dconf: Failed to execute child process “dbus-launch” (No such file or directory)
Traceback (most recent call last):
  File "/usr/share/AKBL/BlockTesting/BlockTesting.py", line 160, in on_button_connect_clicked
    self.button_connect.set_active(False)
AttributeError: 'NoneType' object has no attribute 'set_active'
```

When i apply the changes>

```
2024-03-22 02:54:00 [ERROR]: "/usr/lib/python3.10/AKBL/Bindings.py" __command:
Command=set_lights, arguments=[root,True]
Traceback (most recent call last):
  File "/usr/lib/python3.10/AKBL/Bindings.py", line 52, in __command
    return getattr(self.__pyro, command)(*args)
  File "/usr/lib/python3/dist-packages/Pyro4/core.py", line 185, in __call__
    return self.__send(self.__name, args, kwargs)
  File "/usr/lib/python3/dist-packages/Pyro4/core.py", line 467, in _pyroInvoke
    data = serializer.deserializeData(msg.data, compressed=msg.flags & message.FLAGS_COMPRESSED)
  File "/usr/lib/python3/dist-packages/Pyro4/util.py", line 171, in deserializeData
    return self.loads(data)
  File "/usr/lib/python3/dist-packages/Pyro4/util.py", line 614, in loads
    return self.recreate_classes(serpent.loads(data))
  File "/usr/lib/python3/dist-packages/Pyro4/util.py", line 416, in recreate_classes
    return self.dict_to_class(literal)
  File "/usr/lib/python3/dist-packages/Pyro4/util.py", line 633, in dict_to_class
    return super(SerpentSerializer, cls).dict_to_class(data)
  File "/usr/lib/python3/dist-packages/Pyro4/util.py", line 395, in dict_to_class
    raise errors.SerializeError("unsupported serialized class: " + classname)
Pyro4.errors.SerializeError: unsupported serialized class: usb.core.USBError
```

Thanks!!!

**Comment by rsm-gh** [comment]
Hello @PyroVooDoo ,

I just fixed the following error on the block testing window:

```BlockTesting.py:10291): dconf-WARNING **: 02:50:16.142: failed to commit changes to dconf: Failed to execute child process “dbus-launch” (No such file or directory)
Traceback (most recent call last):
  File "/usr/share/AKBL/BlockTesting/BlockTesting.py", line 160, in on_button_connect_clicked
    self.button_connect.set_active(False)
AttributeError: 'NoneType' object has no attribute 'set_active'```

You can download the stable branch from GIT and re-installed it, it should be fixed.


Regarding the USB error, there's not much that I can do. Maybe try to edit `/usr/bin/akbl`, uncomment the following line `#export LD_PRELOAD=/usr/share/AKBL/libusb-1.0.so.0` and restart your computer. If that doesn't work, I'm sorry but I will not be able to help you.

Best regards,
rsm~

**Comment by rsm-gh** [comment]
Duplicated of https://github.com/rsm-gh/akbl/issues/89
