### ISSUE TITLE
Error while running 

### ISSUE THREAD

**Issue by tr1xem** [rsm-gh/akbl#125]
```
CCParser Warning: the path to the configuration file does not exists
/home/saumya/.config/akbl.ini
Traceback (most recent call last):
  File "/usr/share/AKBL/GUI/main.py", line 40, in do_activate
    self.__gui = MainWindow(application=self)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/AKBL/GUI/MainWindow.py", line 136, in __init__
    self.__theme = theme_factory.create_default_theme(self.__computer, self.__paths._themes_dir)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/AKBL/Theme/factory.py", line 34, in create_default_theme
    theme.save()
  File "/usr/lib/python3/AKBL/Theme/Theme.py", line 84, in save
    with open(self.__path, encoding='utf-8', mode='w') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: ''

** (main.py:3864): WARNING **: 22:29:11.815: AT-SPI: Could not obtain desktop path or name


** (main.py:3864): WARNING **: 22:29:11.819: atk-bridge: GetRegisteredEvents returned message with unknown signature

** (main.py:3864): WARNING **: 22:29:11.819: atk-bridge: get_device_events_reply: unknown signature
Traceback (most recent call last):
  File "/usr/share/AKBL/GUI/MainWindow.py", line 194, in quit
    self.__thread_scan_daemon.do_run = False
    ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'MainWindow' object has no attribute '_MainWindow__thread_scan_daemon'. Did you mean: '_MainWindow__on_thread_scan_daemon'?
```

Device Dell G15 5530

**Comment by tr1xem** [comment]
Also the daemon is running but it still shows not running

**Comment by rsm-gh** [comment]
Hello @tr1xem ,

1) I have made some modifications to debug your problem when saving themes, please download the new version and run it to see the new error message. Probably after that I'll be able to fix it.

2) If the daemon is running, but `akbl --ping` says its not, its probably because is not able to detect your hardware. You need to attach the installation log.

Regards,
rsm

**Comment by tr1xem** [comment]
If the daemon is running, but akbl --ping says its not, its probably because is not able to detect your hardware. You need to attach the installation log.
This says True but the app says daemon not running
Logs
```
[1/5] Removing previous versions..

 Disabling the systemd daemon...
Removed '/etc/systemd/system/basic.target.wants/akbl.service'.

 Removing the python links..
/usr/lib/python3.12/AKBL link removed

 Removing the software files and directories..
removed.f: /usr/share/applications/com.senties-martinelli.AKBL.desktop
removed.f: /usr/bin/akbl
removed.d: /usr/share/AKBL
removed.d: /usr/share/doc/AKBL
removed.d: /usr/lib/python3/AKBL

[2/5] Installing the software files...
installing: /usr/bin
installing: /usr/share/applications
installing: /usr/share/AKBL
installing: /usr/share/AKBL/test
installing: /usr/share/AKBL/computers
installing: /usr/share/AKBL/GUI
installing: /usr/share/AKBL/GUI/ColorChooserToolbar
installing: /usr/share/AKBL/GUI/img
installing: /usr/share/AKBL/BlockTesting
installing: /usr/share/AKBL/Indicator
installing: /usr/share/AKBL/Indicator/img
installing: /usr/share/AKBL/ModelChooser
installing: /usr/share/doc/AKBL
installing: /usr/share/doc/AKBL/BusData
installing: /usr/share/doc/AKBL/BusData/Data
installing: /usr/share/doc/AKBL/ImagesPreview
installing: /usr/share/doc/AKBL/Licenses
installing: /usr/share/doc/AKBL/Programming
installing: /usr/share/doc/AKBL/Programming/class_diagrams
installing: /usr/lib/python3/AKBL
installing: /usr/lib/python3/AKBL/Engine
installing: /usr/lib/python3/AKBL/Computer
installing: /usr/lib/python3/AKBL/Theme
installing: /usr/lib/systemd/system

[3/5] Creating the python links...
linked python3.12

[4/5] Choosing the computer model...

[5/5] Enabling the daemon...
Created symlink '/etc/systemd/system/basic.target.wants/akbl.service' → '/usr/lib/systemd/system/akbl.service'.
AKBL ping... True

The installation has finished. If you have any window of the software (GUI, BlockTesting, Bindings script, etc..) or the indicator is running, you must restart them.

```

**Comment by tr1xem** [comment]
I guess its not implimented well for g15 could i help in any way?

**Comment by rsm-gh** [comment]
The daemon is running and is able to connect with your akbl device, but it is not able to send commands.

So I’ll close this bug because the theme error is fixed, and you can follow the USB core overflow error in the G15 Issues that are already created.
