### ISSUE TITLE
Problems under ubuntu & derivates

### ISSUE THREAD

**Issue by samuaz** [rsm-gh/akbl#15]
i recently switch from manjaro to kde-neon that is ubuntu based and i have this problem when i try to start with the indicator or `setsid alienware-kbl --start-daemon`:

`module 'Pyro4' has no attribute 'expose' `

thanks for your work!

**Comment by rsm-gh** [comment]
Hi! I'll update the installation instructions because that's actually a common problem for some users. Check at this [bug #9](https://github.com/rsm-gh/alienware-kbl/issues/9)   and if you have a problem let me know :)

**Comment by samuaz** [comment]
hi thanks that solve that error but now i have this when i try to select a color

(GUI.py:4494): Gtk-WARNING **: /build/gtk+3.0-6ZPWga/gtk+3.0-3.18.9/./gtk/gtkliststore.c:516: Invalid type (null)

Traceback (most recent call last):
  File "/usr/share/alienware-kbl/ZoneWidget.py", line 269, in on_drawingarea_click
    self.create_gradient(widget, self.cr, 1)
AttributeError: 'Zone' object has no attribute 'cr'

any idea? thanks

**Comment by rsm-gh** [comment]
I have old memories that the bug that you're reporting already happened long time ago under ubuntu based distributions.

I'm going to try the software under that distro, and I hope I be able to fix it!

**Comment by samuaz** [comment]
the serivce work i can use it with terminal, the problem is in the user interface, maybe a gtk/python

**Comment by rsm-gh** [comment]
Originally submitted by @KickinWingAnimalDoctor 

Ubuntu Gnome 16.04 LTS

I have attempted to modify the Computers.py file changing the existing Alienware13 "ID Product"  to `0x0529` but when running `alienware-kbl --start-daemon` I get

```$ sudo alienware-kbl --start-daemon
Warning: It was not possible to os.utime the profile path: 
/root/.local/share/alienware-kbl/Default.cfg
Traceback (most recent call last):
  File "/usr/share/alienware-kbl/Daemon.py", line 98, in _iluminate_keyboard
    os.utime(self.theme.path, None)
AttributeError: 'Daemon' object has no attribute 'theme'

Traceback (most recent call last):
  File "/usr/share/alienware-kbl/Daemon.py", line 105, in _iluminate_keyboard
    self._indicator_pyro.load_profiles(list(Configuration.profiles.keys()), self.profile_name, self._lights_state)
AttributeError: 'bool' object has no attribute 'load_profiles'

Traceback (most recent call last):
  File "/usr/share/alienware-kbl/Daemon.py", line 359, in <module>
    ConnectDaemon()
  File "/usr/share/alienware-kbl/Daemon.py", line 40, in __init__
    uri=self.daemon.register(Daemon(self))
  File "/usr/share/alienware-kbl/Daemon.py", line 87, in __init__
    self.set_lights(self._user, self._ccp.get_bool_defval('boot', True))
  File "/usr/share/alienware-kbl/Daemon.py", line 239, in set_lights
    self._iluminate_keyboard()
  File "/usr/share/alienware-kbl/Daemon.py", line 121, in _iluminate_keyboard
    self._controller.Write_Conf()
  File "/usr/share/alienware-kbl/Engine.py", line 179, in Write_Conf
    self.WaitForOk()
  File "/usr/share/alienware-kbl/Engine.py", line 255, in WaitForOk
    self.Get_State()
  File "/usr/share/alienware-kbl/Engine.py", line 271, in Get_State
    msg = self.driver.ReadDevice(request)
  File "/usr/share/alienware-kbl/Engine.py", line 120, in ReadDevice
    msg = self.dev.ctrl_transfer(self.READ_REQUEST_TYPE, self.READ_REQUEST, self.READ_VALUE, self.READ_INDEX, len(msg[0].packet))
  File "/usr/lib/python3/dist-packages/usb/core.py", line 971, in ctrl_transfer
    self.__get_timeout(timeout))
  File "/usr/lib/python3/dist-packages/usb/backend/libusb0.py", line 528, in ctrl_transfer
    timeout
  File "/usr/lib/python3/dist-packages/usb/backend/libusb0.py", line 380, in _check
    raise USBError(errmsg, ret)
usb.core.USBError: [Errno None] b'error sending control message: Value too large for defined data type'
```

Any help is appreciated, thanks!

**Comment by rsm-gh** [comment]
I just tested the program under `6.04.2-desktop-amd64` and after submitting this [commit](https://github.com/rsm-gh/alienware-kbl/pull/21/commits/57e98ab675c8a9a748d4b157428fbd6c32ca661f) everything worked alright (the bug was non Ubuntu related).

Then, when making a test under `neon-useredition-20170209-1018-amd64` I got the `ZoneWidget` error that was previously mentioned. In the following days I'll try to find a fix for this.

**Comment by great-qwerty** [comment]
Regarding the error reported by @KickinWingAnimalDoctor - there's a typo in Daemon.py on the mentioned line. Just need to replace "os.utime(self.theme.path, None)" with "os.utime(self._theme.path, None)". It doesn't work on my Area 51 R1, but at least that error is fixed :)

**Comment by rsm-gh** [comment]
@great-qwerty Thanks for pointing it ! I've commit the fix.

**Comment by great-qwerty** [comment]
Okay, after digging around the issue I faced, my only option is to ask you for help. My error looks like that:
```
[root@stinson alienware-kbl]# /bin/bash -c "/usr/bin/alienware-kbl --start-daemon"
Traceback (most recent call last):
  File "/usr/share/alienware-kbl/Daemon.py", line 114, in _iluminate_keyboard
    self._indicator_pyro.load_profiles(
AttributeError: 'bool' object has no attribute 'load_profiles'

Traceback (most recent call last):
  File "/usr/share/alienware-kbl/Daemon.py", line 367, in <module>
    ConnectDaemon()
  File "/usr/share/alienware-kbl/Daemon.py", line 41, in __init__
    uri = self.daemon.register(Daemon(self))
  File "/usr/share/alienware-kbl/Daemon.py", line 94, in __init__
    self.set_lights(self._user, self._ccp.get_bool_defval('boot', True))
  File "/usr/share/alienware-kbl/Daemon.py", line 251, in set_lights
    self._iluminate_keyboard()
  File "/usr/share/alienware-kbl/Daemon.py", line 133, in _iluminate_keyboard
    self._controller.Write_Conf()
  File "/usr/share/alienware-kbl/Engine.py", line 195, in Write_Conf
    self.WaitForOk()
  File "/usr/share/alienware-kbl/Engine.py", line 282, in WaitForOk
    self.Get_State()
  File "/usr/share/alienware-kbl/Engine.py", line 298, in Get_State
    msg = self.driver.ReadDevice(request)
  File "/usr/share/alienware-kbl/Engine.py", line 135, in ReadDevice
    msg[0].packet))
  File "/usr/lib/python3/dist-packages/usb/core.py", line 971, in ctrl_transfer
    self.__get_timeout(timeout))
  File "/usr/lib/python3/dist-packages/usb/backend/libusb1.py", line 819, in ctrl_transfer
    timeout))
  File "/usr/lib/python3/dist-packages/usb/backend/libusb1.py", line 552, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 32] Pipe error
```
The phrase "AttributeError: 'bool' object has no attribute 'load_profiles'" seems true, because "self._indicator_pyro = False"... Any ideas why this may happen? Thanks in advance.

**Comment by rsm-gh** [comment]
Hi, actually the first error :

```
Traceback (most recent call last):
  File "/usr/share/alienware-kbl/Daemon.py", line 114, in _iluminate_keyboard
    self._indicator_pyro.load_profiles(
AttributeError: 'bool' object has no attribute 'load_profiles'
```

It's just a warning because there's none indicator running, I'll improve the debug messages to avoid that kind of confusions.


The real problem here is:
```
Traceback (most recent call last):
  File "/usr/share/alienware-kbl/Daemon.py", line 367, in <module>
    ConnectDaemon()
  File "/usr/share/alienware-kbl/Daemon.py", line 41, in __init__
    uri = self.daemon.register(Daemon(self))
  File "/usr/share/alienware-kbl/Daemon.py", line 94, in __init__
    self.set_lights(self._user, self._ccp.get_bool_defval('boot', True))
  File "/usr/share/alienware-kbl/Daemon.py", line 251, in set_lights
    self._iluminate_keyboard()
  File "/usr/share/alienware-kbl/Daemon.py", line 133, in _iluminate_keyboard
    self._controller.Write_Conf()
  File "/usr/share/alienware-kbl/Engine.py", line 195, in Write_Conf
    self.WaitForOk()
  File "/usr/share/alienware-kbl/Engine.py", line 282, in WaitForOk
    self.Get_State()
  File "/usr/share/alienware-kbl/Engine.py", line 298, in Get_State
    msg = self.driver.ReadDevice(request)
  File "/usr/share/alienware-kbl/Engine.py", line 135, in ReadDevice
    msg[0].packet))
  File "/usr/lib/python3/dist-packages/usb/core.py", line 971, in ctrl_transfer
    self.__get_timeout(timeout))
  File "/usr/lib/python3/dist-packages/usb/backend/libusb1.py", line 819, in ctrl_transfer
    timeout))
  File "/usr/lib/python3/dist-packages/usb/backend/libusb1.py", line 552, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 32] Pipe error
```

And it is probably an error from `python-usb` or `libusb`... which is kinda strange because I recently tested the software under Ubuntu and it worked alright.

In a [recent bug](https://github.com/rsm-gh/alienware-kbl/issues/17), @KickinWingAnimalDoctor  posted:

> Hi rsm-gh,
> 
> Good news! I have gotten everything to work. I had to force alienware-kbl to use the libusb version obtained from here: https://github.com/libusb/libusb
> 
> After this I had to edit the value in Computers.py.  "DATA_LENGTH = 9" was changed to 12. 
> 
> I am still testing colors and other things but the leds come on and off on command. Thanks again for all your help!

Which may help you. 

Anyways, I'll try to give it a look after finishing some big changes that I'm doing to the software. I'm currently re-writing most of the code so it be easier to understand & maintain.

If you have more info/details/problems/etc don't hesitate to post it :)

**Comment by rsm-gh** [comment]
Closed because [everything seems to work](https://github.com/rsm-gh/akbl/issues/61).
