### ISSUE TITLE
unsupported serialized class: usb.core.USBError, usb.core.USBError: [Errno 75] Overflow

### ISSUE THREAD

**Issue by rsm-gh** [rsm-gh/akbl#40]
### This bug is affecting many people and I'm not able of fixing it because I can not reproduce it. If you live in the E.U. and you would agree to lend me your computer, contact me! We may organize something so this bug can be closed.

____________________________________________________________

Many people is having the following error: 

```
ERROR from `/usr/share/AlienwareKBL/Bindings.py` on method `_command`:
Command=set_lights, arguments=[root,False]
Traceback (most recent call last):
  File "/usr/share/AlienwareKBL/Bindings.py", line 54, in _command
    response = getattr(self._pyro, command)(*args)
  File "/home/bassim/.local/lib/python3.6/site-packages/Pyro4/core.py", line 187, in __call__
    return self.__send(self.__name, args, kwargs)
  File "/home/bassim/.local/lib/python3.6/site-packages/Pyro4/core.py", line 463, in _pyroInvoke
    data = serializer.deserializeData(msg.data, compressed=msg.flags & message.FLAGS_COMPRESSED)
  File "/home/bassim/.local/lib/python3.6/site-packages/Pyro4/util.py", line 170, in deserializeData
    return self.loads(data)
  File "/home/bassim/.local/lib/python3.6/site-packages/Pyro4/util.py", line 598, in loads
    return self.recreate_classes(serpent.loads(data))
  File "/home/bassim/.local/lib/python3.6/site-packages/Pyro4/util.py", line 415, in recreate_classes
    return self.dict_to_class(literal)
  File "/home/bassim/.local/lib/python3.6/site-packages/Pyro4/util.py", line 617, in dict_to_class
    return super(SerpentSerializer, cls).dict_to_class(data)
  File "/home/bassim/.local/lib/python3.6/site-packages/Pyro4/util.py", line 394, in dict_to_class
    raise errors.SerializeError("unsupported serialized class: " + classname)
Pyro4.errors.SerializeError: unsupported serialized class: usb.core.USBError
```
and even if `Pyro` seems to be the problem, the real problem is coming from `usb.core`. 

By using the block testing window (`akbl --block-testing` as root), it is possible to track it since the window doesn't use `Pyro`:

```
Traceback (most recent call last):
  File "/usr/share/AlienwareKBL/ADDONS/BlockTesting/BlockTesting.py", line 335, in on_button_block_testing_lights_off_clicked
    self._testing_controller.add_reset_line(self._computer.RESET_ALL_LIGHTS_OFF)
  File "/usr/share/AlienwareKBL/Engine/Core/Controller.py", line 77, in add_reset_line
    while not self._device_is_ready():
  File "/usr/share/AlienwareKBL/Engine/Core/Controller.py", line 48, in _device_is_ready
    msg = self._driver.read_device(constructor)
  File "/usr/share/AlienwareKBL/Engine/Core/Driver.py", line 107, in read_device
    msg = self._device.ctrl_transfer(self.READ_REQUEST_TYPE, self.READ_REQUEST, self.READ_VALUE, self.READ_INDEX, len(msg[0].packet))
  File "/usr/lib/python3.6/site-packages/usb/core.py", line 1043, in ctrl_transfer
    self.__get_timeout(timeout))
  File "/usr/lib/python3.6/site-packages/usb/backend/libusb1.py", line 883, in ctrl_transfer
    timeout))
  File "/usr/lib/python3.6/site-packages/usb/backend/libusb1.py", line 595, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 75] Overflow
```

The real problem is then an **[Errno 75] Overflow** coming by `usb.core` and it only happens with some computer models.  Sadly we haven't been able of finding a solution. 

The following bug reports are the ones containing related information: 

* [USB error 75 Overflow on Kubuntu 17.10, Alienware 15 R3](https://github.com/rsm-gh/alienware-kbl/issues/39)
* [Unable to start the GUI due to Pyro](https://github.com/rsm-gh/alienware-kbl/issues/35)
* [**Add support to the Alienware 17 R4 computer**](https://github.com/rsm-gh/alienware-kbl/issues/29)
* [**Add support to the Alienware 13 R3 computer**](https://github.com/rsm-gh/alienware-kbl/issues/17)
* [Add support to the Alienware 15 R3 computer](https://github.com/rsm-gh/alienware-kbl/issues/8)

**Comment by josedellabosca** [comment]
I can start the gui, the error messages appears when trying to send data to the usb controller.
i am using Gentoo x64

> ERROR from `/usr/share/AlienwareKBL/Bindings.py` on method `_command`:
Command=set_lights, arguments=[root,False]
Traceback (most recent call last):
  File "/usr/share/AlienwareKBL/Bindings.py", line 54, in _command
    response = getattr(self._pyro, command)(*args)
  File "/usr/lib64/python3.5/site-packages/Pyro4/core.py", line 185, in __call__
    return self.__send(self.__name, args, kwargs)
  File "/usr/lib64/python3.5/site-packages/Pyro4/core.py", line 454, in _pyroInvoke
    data = serializer.deserializeData(msg.data, compressed=msg.flags & message.FLAGS_COMPRESSED)
  File "/usr/lib64/python3.5/site-packages/Pyro4/util.py", line 170, in deserializeData
    return self.loads(data)
  File "/usr/lib64/python3.5/site-packages/Pyro4/util.py", line 558, in loads
    return self.recreate_classes(serpent.loads(data))
  File "/usr/lib64/python3.5/site-packages/Pyro4/util.py", line 411, in recreate_classes
    return self.dict_to_class(literal)
  File "/usr/lib64/python3.5/site-packages/Pyro4/util.py", line 575, in dict_to_class
    return super(SerpentSerializer, cls).dict_to_class(data)
  File "/usr/lib64/python3.5/site-packages/Pyro4/util.py", line 390, in dict_to_class
    raise errors.SerializeError("unsupported serialized class: " + classname)
Pyro4.errors.SerializeError: unsupported serialized class: usb.core.USBError

>

**Comment by diveyez** [comment]
Its pyro, 
root@alienware:/home/diveyez# alienware-kbl --daemon-is-on
Traceback (most recent call last):
  File "/usr/share/AlienwareKBL/ADDONS/DefaultArguments.py", line 26, in <module>
    from Bindings import Bindings
  File "/usr/share/AlienwareKBL/Bindings.py", line 22, in <module>
    import Pyro4
ImportError: No module named 'Pyro4'

**Comment by barci2** [comment]
Have anything changed with this bug?

**Comment by BlackLight337** [comment]
Hi, I got that same error while trying to run it finally it works! I got the 15 one. Finally I can turn off the lights when using battery. Ty so much. I like to thank you here because I can't seem to find your contacts on the website.

**Comment by rsm-gh** [comment]
@BlackLight337 I'm happy it is now working for you and I hope that we can totally fix this part in the future so everything works alright :)

rsm

**Comment by gggauravgandhi** [comment]
Its not working on my Alienware R313, same error while trying to do `akbl --off`

**Comment by pulver22** [comment]
Same problem on m15 while running akbl --on

**Comment by YozoraWolf** [comment]
Having the same issue on Dell G15 5515 (US). Nothing works.

**Comment by c0pper** [comment]
Same issue on Alienware Aurora R10

**Comment by tr1xem** [comment]
https://github.com/tr1xem/AWCC > Fix for G15
