### ISSUE TITLE
Arch / Manjaro Alien 15 R3 total malfunction

### ISSUE THREAD

**Issue by raphaelcasimir** [rsm-gh/akbl#44]
# System information

+ Distribution name: Manjaro rolling release
+ Distribution version: 17.11 (last)
+ Python version: 3.7.0
+ Computer model: Alienware 15 R3
+ Output of the command `alienware-kbl --daemon-is-on`:
```sh
sudo akbl --daemon-is-on         
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/Pyro4/core.py", line 515, in connect_and_handshake
    sslContext=sslContext)
  File "/usr/lib/python3.7/site-packages/Pyro4/socketutil.py", line 307, in createSocket
    sock.connect(connect)
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.7/AKBL/Bindings.py", line 95, in reload_address
    pyro.ping()
  File "/usr/lib/python3.7/site-packages/Pyro4/core.py", line 275, in __getattr__
    self._pyroGetMetadata()
  File "/usr/lib/python3.7/site-packages/Pyro4/core.py", line 615, in _pyroGetMetadata
    self.__pyroCreateConnection()
  File "/usr/lib/python3.7/site-packages/Pyro4/core.py", line 596, in __pyroCreateConnection
    connect_and_handshake(conn)
  File "/usr/lib/python3.7/site-packages/Pyro4/core.py", line 549, in connect_and_handshake
    raise ce
Pyro4.errors.CommunicationError: cannot connect to ('localhost', 44421): [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/AKBL/launch/default_arguments.py", line 29, in <module>
    AKBLConnection = Bindings()
  File "/usr/lib/python3.7/AKBL/Bindings.py", line 35, in __init__
    self.reload_address()
  File "/usr/lib/python3.7/AKBL/Bindings.py", line 104, in reload_address
    print_error(format_exc())
TypeError: 'bool' object is not callable

```
+ Output of `sudo akbl --off`
```sh
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/Pyro4/core.py", line 515, in connect_and_handshake
    sslContext=sslContext)
  File "/usr/lib/python3.7/site-packages/Pyro4/socketutil.py", line 307, in createSocket
    sock.connect(connect)
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.7/AKBL/Bindings.py", line 95, in reload_address
    pyro.ping()
  File "/usr/lib/python3.7/site-packages/Pyro4/core.py", line 275, in __getattr__
    self._pyroGetMetadata()
  File "/usr/lib/python3.7/site-packages/Pyro4/core.py", line 615, in _pyroGetMetadata
    self.__pyroCreateConnection()
  File "/usr/lib/python3.7/site-packages/Pyro4/core.py", line 596, in __pyroCreateConnection
    connect_and_handshake(conn)
  File "/usr/lib/python3.7/site-packages/Pyro4/core.py", line 549, in connect_and_handshake
    raise ce
Pyro4.errors.CommunicationError: cannot connect to ('localhost', 44421): [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/AKBL/launch/default_arguments.py", line 29, in <module>
    AKBLConnection = Bindings()
  File "/usr/lib/python3.7/AKBL/Bindings.py", line 35, in __init__
    self.reload_address()
  File "/usr/lib/python3.7/AKBL/Bindings.py", line 104, in reload_address
    print_error(format_exc())
TypeError: 'bool' object is not callable

```
# Bug description
No cli command does anything to the lights, and the graphical interface can't apply any changes.
Either with sudo or not. Arch linux community utility 'alienfx' works to some extent (not for the screen side lights).

**Comment by rsm-gh** [comment]
Hi @raphaelcasimir,

I just commited some bug fixes to have a better debug message. Can you re-install the stable branch and repost the state of the following commands?

- `systemctl status akbl` ( as a normal user, not as root )
- `akbl --off`  ( as a normal user, not as root )

To use `akbl` it is not necessary to be root. The only command that needs root permission is `akbl --start-daemon`, but you don't need to use it yet.

Keep me updated ! We will make it work :),
rsm

**Comment by raphaelcasimir** [comment]
Thanks a lot ! Unfortunately I am not using Manjaro anymore due to its global quality regression. I will try to use akbl under mint shortly and see if the problem persists. I will keep you updated.

**Comment by rsm-gh** [comment]
@raphaelcasimir , to avoid having duplicated content I'm going to close this issue and please continue reporting your problems under this one: [Add support to the Alienware 15 R3 computer](https://github.com/rsm-gh/akbl/issues/8).

By the way, an user just committed some fixes to this computer so maybe now it will work even better. 

Regards,
rsm
