### ISSUE TITLE
Problem with Alienware 13 R1

### ISSUE THREAD

**Issue by spramij** [rsm-gh/akbl#56]
# System information

+ Distribution name: Manjaro 
+ Distribution version: 18.0.2
+ Python3 version: 3.7.2
+ akbl version: 2019.01.13
+ Computer model: Alienware 13 R1
+ Daemon status: False

# Bug description

Daemon won't start, `systemctl status akbl` returns
```
akbl.service - AKBL Daemon
   Loaded: loaded (/usr/lib/systemd/system/akbl.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Fri 2019-01-18 13:49:26 NST; 27s ago
  Process: 28809 ExecStart=/bin/bash -c /usr/bin/akbl --start-daemon (code=exited, status=1/FAILURE)
 Main PID: 28809 (code=exited, status=1/FAILURE)

Jan 18 13:49:26 Jadoo systemd[1]: Started AKBL Daemon.
Jan 18 13:49:26 Jadoo bash[28809]: ERROR from `/usr/lib/python3.7/AKBL/Engine/Controller.py` on method `__init__`:
Jan 18 13:49:26 Jadoo bash[28809]: The computer is not supported.
Jan 18 13:49:26 Jadoo systemd[1]: akbl.service: Main process exited, code=exited, status=1/FAILURE
Jan 18 13:49:26 Jadoo systemd[1]: akbl.service: Failed with result 'exit-code'.
```

I made sure to install all the latest dependencies

**Comment by rsm-gh** [comment]
hi  spramij,
The problem is that your computer model is not being recognized:
```
Jan 18 13:49:26 Jadoo bash[28809]: The computer is not supported.
```

To continue investigating the problem I need you to copy-paste me the `detected USB data` text of the installation window:
![screenshot_2019-01-18_19-14-27](https://user-images.githubusercontent.com/11134652/51404943-33fe8880-1b55-11e9-8b9f-d535adf8e020.png)

a screenshoot of the window may also be useful !

regards,
rsm

**Comment by spramij** [comment]
Hey, 

Here is the `Detected USB data` 

```
Device: ID 187c:0527 Alienware Corporation 
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               0.02
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x187c Alienware Corporation
  idProduct          0x0527 
  bcdDevice            0.00
  iManufacturer           1 Alienware
  iProduct                2 AW13
  iSerial                 3 13.0
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x0029
    bNumInterfaces          1
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xe0
      Self Powered
      Remote Wakeup
    MaxPower                0mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      0 
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.01
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      56
          Report Descriptor: (length is 56)
            Item(Global): Usage Page, data= [ 0x00 0xff ] 65280
                            (null)
            Item(Local ): Usage, data= [ 0x01 ] 1
                            (null)
            Item(Main  ): Collection, data= [ 0x01 ] 1
                            Application
            Item(Global): Usage Page, data= [ 0x0c ] 12
                            Consumer
            Item(Local ): Usage, data= [ 0x06 ] 6
                            (null)
            Item(Main  ): Collection, data= [ 0x02 ] 2
                            Logical
            Item(Local ): Usage Minimum, data= [ 0x00 ] 0
                            Unassigned
            Item(Local ): Usage Maximum, data= [ 0x66 ] 102
                            Still
            Item(Global): Logical Minimum, data= [ 0x00 ] 0
            Item(Global): Logical Maximum, data= [ 0x01 ] 1
            Item(Global): Report ID, data= [ 0x01 ] 1
            Item(Global): Report Size, data= [ 0x08 ] 8
            Item(Global): Report Count, data= [ 0x08 ] 8
            Item(Main  ): Input, data= [ 0x02 ] 2
                            Data Variable Absolute No_Wrap Linear
                            Preferred_State No_Null_Position Non_Volatile Bitfield
            Item(Main  ): End Collection, data=none
            Item(Global): Usage Page, data= [ 0x14 ] 20
                            Alphanumeric Display
            Item(Local ): Usage, data= [ 0x2b ] 43
                            Character Report
            Item(Main  ): Collection, data= [ 0x02 ] 2
                            Logical
            Item(Local ): Usage Minimum, data= [ 0x01 ] 1
                            Alphanumeric Display
            Item(Local ): Usage Maximum, data= [ 0x66 ] 102
                            (null)
            Item(Global): Logical Minimum, data= [ 0x00 ] 0
            Item(Global): Logical Maximum, data= [ 0x01 ] 1
            Item(Global): Report ID, data= [ 0x02 ] 2
            Item(Global): Report Size, data= [ 0x08 ] 8
            Item(Global): Report Count, data= [ 0x08 ] 8
            Item(Local ): Usage, data= [ 0x2c ] 44
                            Display Data
            Item(Main  ): Output, data= [ 0x02 ] 2
                            Data Variable Absolute No_Wrap Linear
                            Preferred_State No_Null_Position Non_Volatile Bitfield
            Item(Main  ): End Collection, data=none
            Item(Main  ): End Collection, data=none
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x000a  1x 10 bytes
        bInterval              10
Device Status:     0x0000
  (Bus Powered)
```

![screenshot](https://user-images.githubusercontent.com/38168727/51406582-24227c80-1b34-11e9-92b8-6f6c16a4cbbe.png)


Clicking on the little box next to my device name doesn't change anything.

Thanks for the help!

**Comment by spramij** [comment]
Fixed it by manually creating the folder AKBL in `/etc/`, adding a file `default_computer.ini`, and clicking on the checkbox on the correct model name.

If it's of any help, here's the output from running `setup`

```
*********************************** 
 *** Installing AKBL v2019.01.13 *** 
 *********************************** 


[1/5] Removing previous versions..

Disabling the systemd daemon...

Removing the software links..

Removing the software files and directories..

[2/5] Installing the software files...
 Copying the software files...
installing: /usr/bin
installing: /usr/share/applications
installing: /usr/share/AKBL
install: omitting directory '/home/[name]/Downloads/akbl-stable/akbl-stable/usr/share/AKBL/computers'
install: omitting directory '/home/[name]/Downloads/akbl-stable/akbl-stable/usr/share/AKBL/launch'
install: omitting directory '/home/[name]/Downloads/akbl-stable/akbl-stable/usr/share/AKBL/test'
installing: /usr/share/AKBL/computers
installing: /usr/share/AKBL/launch
installing: /usr/share/AKBL/test
installing: /usr/share/doc/AKBL
install: omitting directory '/home/[name]/Downloads/akbl-stable/akbl-stable/usr/share/doc/AKBL/BusData'
install: omitting directory '/home/[name]/Downloads/akbl-stable/akbl-stable/usr/share/doc/AKBL/ImagesPreview'
install: omitting directory '/home/[name]/Downloads/akbl-stable/akbl-stable/usr/share/doc/AKBL/Licenses'
install: omitting directory '/home/[name]/Downloads/akbl-stable/akbl-stable/usr/share/doc/AKBL/Programming'
installing: /usr/share/doc/AKBL/BusData
install: omitting directory '/home/[name]/Downloads/akbl-stable/akbl-stable/usr/share/doc/AKBL/BusData/Data'
installing: /usr/share/doc/AKBL/BusData/Data
installing: /usr/share/doc/AKBL/ImagesPreview
installing: /usr/share/doc/AKBL/Licenses
installing: /usr/share/doc/AKBL/Programming
install: omitting directory '/home/[name]/Downloads/akbl-stable/akbl-stable/usr/share/doc/AKBL/Programming/class_diagrams'
installing: /usr/share/doc/AKBL/Programming/class_diagrams
installing: /usr/lib/systemd/system
installing: /usr/lib/python3/AKBL
install: omitting directory '/home/[name]/Downloads/akbl-stable/akbl-stable/usr/lib/python3/AKBL/Addons'
install: omitting directory '/home/[name]/Downloads/akbl-stable/akbl-stable/usr/lib/python3/AKBL/Data'
install: omitting directory '/home/[name]/Downloads/akbl-stable/akbl-stable/usr/lib/python3/AKBL/Engine'
installing: /usr/lib/python3/AKBL/Data
install: omitting directory '/home/[name]/Downloads/akbl-stable/akbl-stable/usr/lib/python3/AKBL/Data/Computer'
install: omitting directory '/home/[name]/Downloads/akbl-stable/akbl-stable/usr/lib/python3/AKBL/Data/Theme'
installing: /usr/lib/python3/AKBL/Data/Computer
installing: /usr/lib/python3/AKBL/Data/Theme
installing: /usr/lib/python3/AKBL/Engine
installing: /usr/lib/python3/AKBL/Addons
install: omitting directory '/home/[name]/Downloads/akbl-stable/akbl-stable/usr/lib/python3/AKBL/Addons/BlockTesting'
install: omitting directory '/home/[name]/Downloads/akbl-stable/akbl-stable/usr/lib/python3/AKBL/Addons/GUI'
install: omitting directory '/home/[name]/Downloads/akbl-stable/akbl-stable/usr/lib/python3/AKBL/Addons/Indicator'
install: omitting directory '/home/[name]/Downloads/akbl-stable/akbl-stable/usr/lib/python3/AKBL/Addons/ModelChooser'
installing: /usr/lib/python3/AKBL/Addons/GUI
install: omitting directory '/home/[name]/Downloads/akbl-stable/akbl-stable/usr/lib/python3/AKBL/Addons/GUI/ColorChooserToolbar'
install: omitting directory '/home/[name]/Downloads/akbl-stable/akbl-stable/usr/lib/python3/AKBL/Addons/GUI/images'
installing: /usr/lib/python3/AKBL/Addons/GUI/ColorChooserToolbar
installing: /usr/lib/python3/AKBL/Addons/GUI/images
installing: /usr/lib/python3/AKBL/Addons/BlockTesting
installing: /usr/lib/python3/AKBL/Addons/Indicator
install: omitting directory '/home/[name]/Downloads/akbl-stable/akbl-stable/usr/lib/python3/AKBL/Addons/Indicator/images'
installing: /usr/lib/python3/AKBL/Addons/Indicator/images
installing: /usr/lib/python3/AKBL/Addons/ModelChooser
 Replacing variables...

[3/5] Creating the python links...
python3   linked (default location)
python3.7 linked


[4/5] Choosing the computer model...
Choose the configuration file from the GTK window that will appear..
The current configuration is: <NONE>
Traceback (most recent call last):
  File "/usr/lib/python3.7/AKBL/Addons/ModelChooser/ModelChooser.py", line 144, in _on_model_change_clicked
    computer_factory.set_default_computer(computer_model)
  File "/usr/lib/python3.7/AKBL/Data/Computer/factory.py", line 110, in set_default_computer
    with open(_SOFTWARE_PATHS._default_computer_file, 'w') as fw:
FileNotFoundError: [Errno 2] No such file or directory: '/etc/AKBL/default_computer.ini'
Default computer updated to: Alienware13R1

[5/5] Enabling the daemon...
Created symlink /etc/systemd/system/basic.target.wants/akbl.service → /usr/lib/systemd/system/akbl.service.

 ************************************* 
 *** AKBL v2019.01.13 is installed *** 
 *
```

**Comment by rsm-gh** [comment]
@spramij 
I see the problem, it actually happened because you closed the dialog without choosing a computer model. To avoid further mistakes by other users I just added a confirmation dialog:

![screenshot_2019-01-18_20-32-49](https://user-images.githubusercontent.com/11134652/51408872-619cff00-1b60-11e9-996b-b43146f8a4af.png)

I'll also add it to the installation instructions.

Thanks for reporting this and also for your feedback!

Regards,
rsm

**Comment by spramij** [comment]
@rsm-gh actually selecting the model wasn't working, if you look at the log in my last reply, when it reaches step 4 and opens the dialog I selected the model, but received an error 
> Traceback (most recent call last):
  File "/usr/lib/python3.7/AKBL/Addons/ModelChooser/ModelChooser.py", line 144, in _on_model_change_clicked
    computer_factory.set_default_computer(computer_model)
  File "/usr/lib/python3.7/AKBL/Data/Computer/factory.py", line 110, in set_default_computer
    with open(_SOFTWARE_PATHS._default_computer_file, 'w') as fw:
FileNotFoundError: [Errno 2] No such file or directory: '/etc/AKBL/default_computer.ini'

I then created the folder and file, and selected it again, and it then worked
> Default computer updated to: Alienware13R1

**Comment by rsm-gh** [comment]
@spramij , 

Yes you're right, by reading your comments I thought that the problem was only the `default_computer.ini` file, but the `/etc/AKB/` [folder creation was missing in](https://github.com/rsm-gh/akbl/commit/2cdf08900c5fee399ee1a2f6d2391380ab3450af) the `Paths()` class.

Thanks for pointing that out !
