### ISSUE TITLE
Cleaning up the configuration file for 15R3

### ISSUE THREAD

**Issue by Soulsuke** [rsm-gh/akbl#58]
I'm trying to clean up the configuration file for 15R3, but there are two issues.

First off, an easy thing I need an advice for:
`[REGION RIGHT_SPEAKER]
	ID=RS
	DESCRIPTION=Side: Top Left
	BLOCK=4096
	SUPPORTED_COMMANDS=15
	CAN_BLINK=True
	CAN_MORPH=True
	CAN_LIGHT=True

[REGION TACTX]
	ID=TX
	DESCRIPTION=Side: Top Right
	BLOCK=8192
	SUPPORTED_COMMANDS=15
	CAN_BLINK=True
	CAN_MORPH=True
	CAN_LIGHT=True

[REGION TOUCH_PAD]
	ID=TP
	DESCRIPTION=Side: Bottom Left
	BLOCK=1024
	SUPPORTED_COMMANDS=15
	CAN_BLINK=True
	CAN_MORPH=True
	CAN_LIGHT=True

[REGION LEFT_SPEAKER]
	ID=LS
	DESCRIPTION=Side: Bottom Right
	BLOCK=2048
	SUPPORTED_COMMANDS=15
	CAN_BLINK=True
	CAN_MORPH=True
	CAN_LIGHT=True`
These 4 regions correspond to different areas of the 15R3, specifically to the side lights on the case. Should the REGION identifiers/IDs change accordingly, or should I simply leave it as is (with only the description changed)?

Then there's the Tact-X issue:
`[REGION POWER_BUTON_EYES]
	ID=PBE
	DESCRIPTION=Tact-X
	BLOCK=16384
	SUPPORTED_COMMANDS=1
	CAN_BLINK=True
	CAN_MORPH=True
	CAN_LIGHT=True`
It corresponds to the power button eyes REGION which cannot be changed anymore. How should such thing be addressed?

**Comment by rsm-gh** [comment]
Hi, 

I just made some commits for adding some doc and security. The doc added into the configuration files is

```python

#*********************************************************************************************************************
#																													 #
#       The configuration file allows to easily add and modify regions. The template for it is the following:        #
#																													 #
#																												     #
# [REGION <UNIQUE_REGION_NAME>]																						 #
# 	ID= <UNIQUE REGION ID>																							 #
# 	DESCRIPTION= <DESCRIPTION>																						 #
#	BLOCK= <INTEGER>																								 #
#	SUPPORTED_COMMANDS= <INTEGER>																					 #
#	CAN_BLINK= <BOOLEAN>																							 #
#	CAN_MORPH= <BOOLEAN>																							 #
#	CAN_LIGHT <BOOLEAN>																						         #
#																													 #
# -> The REGION NAME it is only using for parsing the configuration file. Any unique name can be added.				 #
#																													 #
# -> ID is the field used by the software to order the regions in the interface. The only two id's that should		 #
#    not be changed are PB and PBE. New Id's can be created.				    							         #  
#																													 #
# -> I do not advice to modify the COMMON section.																	 #
#																			 										 #
#           ~ Since AKBL is a communitary project any improvement should be reported ~								 #
#                       to: https://github.com/rsm-gh/akbl/issues 													 #
#        																											 #
#********************************************************************************************************************#
```

does it answer your questions?

**Comment by Soulsuke** [comment]
Just two quick followup questions:
- about "New Id's can be created", does it mean they have to be defined somewhere within the application?
- should I follow any kind of pattern about the naming of these regions/ids on the sides of the laptop?

**Comment by rsm-gh** [comment]
The ID's are defined in that configuration file. You are totally free of choosing the naming, the only requirement is to make them unique. 

But to be honest, there is no interest in modifying the current section and their ids. Beside creating new sections, you should only modify the description.

ex:
```
[REGION FOO]
ID=FAA
DESCRIPTION=Bla bla
BLOCK=8192
SUPPORTED_COMMANDS=15
CAN_BLINK=True
CAN_MORPH=True
CAN_LIGHT=True

[REGION FOO2]
ID=FIFAFU
DESCRIPTION=Bla Bla
BLOCK=1
SUPPORTED_COMMANDS=15
CAN_BLINK=True
CAN_MORPH=True
CAN_LIGHT=True
```

**Comment by Soulsuke** [comment]
I've kept the original IDs in the end, mostly because those marked as speaker left/right need to be affected by `0x1800 primitive speaker-both`.

Although I'm not sure it's related, is there any way I can check how the mousepad area (which is currently not working) is mapped, or is there some documentation I can look up to understand how to help in fixing such issue? I'd really like to help fixing the couple of issues still present for this Alienware model ^^

**Comment by rsm-gh** [comment]
@Soulsuke  I think that the best that you can do is to use the block testing window. If you can't fix your problems with that window, the only solution is to understand the code and how akbl works. There's no documentation and it will demand you a lot of effort and programing skills.

Anyways keep me updated ! I'll merge your work once you've take a look to the whole thing

**Comment by Soulsuke** [comment]
@rsm-gh  Thanks, I'll look at it as soon as I can (but probably won't be anytime before the weekend).
As for the code, we'll see what will happen :p I'm not really versed in Python, but I hope I'll be able to find my way around if needed.... I mean, the entry point is clear enough, that's not something everyone can say :D

**Comment by Soulsuke** [comment]
@rsm-gh Sorry for the late update. I'm trying to use the block testing window (`sudo akbl --block-testing`), but I'm getting an exception every time I try to do something:

> Traceback (most recent call last):
>   File "/usr/lib/python3.7/AKBL/Addons/BlockTesting/BlockTesting.py", line 320, in on_button_block_testing_lights_off_clicked
>     self._testing_controller.add_reset_line(self._computer.RESET_ALL_LIGHTS_OFF)
>   File "/usr/lib/python3.7/AKBL/Engine/Controller.py", line 62, in add_reset_line
>     while not self.__device_is_ready():
>   File "/usr/lib/python3.7/AKBL/Engine/Controller.py", line 114, in __device_is_ready
>     msg = self._driver.read_device(constructor)
>   File "/usr/lib/python3.7/AKBL/Engine/Driver.py", line 122, in read_device
>     len(constructor.get_first_command()))
>   File "/usr/lib/python3.7/site-packages/usb/core.py", line 1043, in ctrl_transfer
>     self.__get_timeout(timeout))
>   File "/usr/lib/python3.7/site-packages/usb/backend/libusb1.py", line 883, in ctrl_transfer
>     timeout))
>   File "/usr/lib/python3.7/site-packages/usb/backend/libusb1.py", line 595, in _check
>     raise USBError(_strerror(ret), ret, _libusb_errno[ret])
> usb.core.USBError: [Errno 75] Overflow

**Comment by rsm-gh** [comment]
Hello,

Yes it is related to #40 , after launching the block testing window and using the `connect` button, you need to set the  General configuration variable `DATA_LENGTH=12`.

By the way, the modification of that variable is what is making that the colors are not correctly applied.

**Comment by Soulsuke** [comment]
@rsm-gh ....sorry, I didn't notice the settings area had a scrollbar! I've just tried out all the available blocks to no avail (with bith bios settings concerning the touchpad backlight).

What can I do to actually get a clue on what's not working? I mean, is it a block device not being recognized, do I have to try with some special options, or anything else?

**Comment by rsm-gh** [comment]
You can't do much beside trying all the possible `region numbers`, and by all the possible, I mean using custom region numbers:

![Screenshot_2019-04-20_16-19-08](https://user-images.githubusercontent.com/11134652/56458523-250fb800-6388-11e9-8326-a26fd47a0b2c.png)

The region `-1` allow you to enter custom values. And by the way, I just committed some fixes to the block testing window general section, it may be a good idea that you download the new version

**Comment by Soulsuke** [comment]
Do these region numbers have to be powers of 2? And is it there any possible danger in trying out random numbers?

.......Even better: about the function used to set up the lights for the various block device, is it aware if has been able to correctly contact the device? I mean, is it possible to differentiate between a valid and invalid block id from its outcome? Or can I try to implement such feature if there's any doc about it?

Another question is, what does the "primitive" directive in config files do for the speakers blocks? May it be relevant somehow??

Sorry for all these questions, I really wish to help if I can :p

**Comment by rsm-gh** [comment]
what `primitive` directive?

**Comment by Soulsuke** [comment]
I meant the `0x1800 primitive speaker-both` line in config files

**Comment by rsm-gh** [comment]
ah ok. No, don't use that, it is just that as an info. And for your other questions:
* Do region numbers have to be powers of 2? Noup, for example, I believe that the region block 1 is used in some configurations
*  is it possible to differentiate between a valid and invalid block id from its outcome? No, I just implemented it in debug mode but there seems to be no interest on it since the output is always 9. You can change into debug mode with the setup file. `DEBUG='True'

**Comment by rsm-gh** [comment]
Hi @Soulsuke I just merged your commit and I was wondering why are you still searching for a  touchpad block [if it is defined in the configuration file](https://github.com/rsm-gh/akbl/blob/593d39bb50fb4d12d63c19af7ee23ec7e34eaa0b/usr/share/AKBL/computers/Alienware15R3.ini#L191). It is not working?

```
[REGION TOUCH_PAD]
	ID=TP
	DESCRIPTION=Touch Pad
	BLOCK=128
	SUPPORTED_COMMANDS=15
	CAN_BLINK=True
	CAN_MORPH=True
CAN_LIGHT=True
```

rsm

**Comment by Soulsuke** [comment]
@rsm-gh Touchpad hasn't been working for a while on 15 R3... I remember it working the time I commented on #17... I tried to find a commit in git history around that time, but it only goes back as far as Nov 3 21:43:59, and it didn't work back then... Is there any chance for the old git history to be still around??

**Comment by rsm-gh** [comment]
@rsm-gh I don't think so but I have an old backup dating of 11 sep 2017. These was the R15R3 values:

```python
class Alienware15(CommonConf):

    def __init__(self):
        super().__init__()
        self.name = TEXT_ALIENWARE15

        self.REGION_RIGHT_KEYBOARD = 0x0001
        self.REGION_RIGHT_CENTER_KEYBOARD = 0x0002
        self.REGION_LEFT_KEYBOARD = 0x8
        self.REGION_LEFT_CENTER_KEYBOARD = 0x4
        self.REGION_LEFT_SPEAKER = 0x800
        self.REGION_RIGHT_SPEAKER = 0x1000
        self.REGION_POWER_BUTTON = 0x0100
        self.REGION_TOUCH_PAD = 0x400
        self.REGION_ALL_BUT_POWER = 0x7fff
        self.REGION_ALIEN_NAME = 0x0040
        self.REGION_ALIEN_HEAD = 0x0020
        self.REGION_MEDIA_BAR = 0x0080
        self.REGION_TACTX = 0x2000
        self.REGION_POWER_BUTTON_EYES = 0x4000
        # 0x1800 primitive speaker-both
```

To get the integer equivalents you can use python print:
```python
>>> print(0x400)
1024
```

**Comment by Soulsuke** [comment]
@rsm-gh Sorry for the late reply, sadly those values are the same as those in the current configuration file... Is there any chance you could share that backup of yours? Just to check if it makes the touchpad works

**Comment by rsm-gh** [comment]
Hi @Soulsuke, this is the oldest version that I have [170911-alienware-kbl-stable.zip](https://github.com/rsm-gh/akbl/files/3142783/170911-alienware-kbl-stable.zip).

**Comment by Soulsuke** [comment]
@rsm-gh sorry for the late reply! I've tried out the code you've provided, but the touchpad still isn't working... Oh well!

**Comment by Soulsuke** [comment]
@rsm-gh hello, sorry for the long delay.

I've been able to run a couple of tests using a Windows 10 on-the-go usb installation... Apparently the touchpad zone data in the configuration file is correct, but akbl is somehow unable  to light it up if it is starts as switched off when the laptop boots up.

If the touchpad backlight is already on during the boot process, akbl is able to turn it off and back on, as well as changing its color.

I'm using the "on" bios setting for the touchpad backlight, as using "auto" just keeps the light off, and I've tried this with both my old firmware (1.8) and the latest one released (1.9.0).

Is there any info I can provide or any tests I can run (both on Linux and Windows) which may help?

**Comment by rsm-gh** [comment]
Hello @Soulsuke ,

That seems interesting but I'm not really sure if I'll be able to investigate about it (my computer lights are almost dead), is the touch pad zone the only one with this problem? Maybe the alienware power button, or the eyes have the same problem. 

rsm

**Comment by rsm-gh** [comment]
@Soulsuke ,

Other think to test is the following:

1. Turn off the bios setting
2. make a reboot
3. launch akbl
4. Set the lights off
5. Set the lights on
6. Check if AKBL works as normal (colors and lights can be set/changed)

**Comment by Soulsuke** [comment]
Just tried that out!

As far as I can tell the only zone affected is the touchpad area, everything else seem to be working as under Windows with the Command Center.

If I set set the bios option "Touchpad Backlight" to "Auto" then that area will stay off, no matter what I do in akbl (I guess the CC lights it up on Windows the same way it also handles the TactX button pressures), the only way I can get it working is by setting the bios option to "On" and keep the area lighted up whenever I shutdown or reboot. Hybernating while the area is off does not seem to cause any issue, as the touchpad can still be controlled via akbl on resume.

For now I've added a systemctl service to run "akbl --on" on shutdown, this way I can get the touchpad backlight working between reboots

**Comment by rsm-gh** [comment]
@Soulsuke that's curious. And have you been able of making USB package sniffing? maybe the command center sends some special package that we ignore.

**Comment by Soulsuke** [comment]
@rsm-gh I have yet to try that, I admit it's not something I've ever tackled, can you give me a starting point about what kind of data I should keep an eye out for? Or should I just save all the raw data sent to the usb device??

I should also report the following use case:
- the laptop boots up with touchpad backlight turned off, so I have no way to turn it on via akbl
- I open akbl and change the touchpad area color from green to red and save the configuration (of course, the area will stil be off)
- shut down the laptop and switch to Windows 10
- during the boot process (before the UI is up, while there is a black splashscreen with the blue windoww logo) the touchpad backlight will turn on AND it will use the color I set via akbl

So it's quite possible the CC sends the command to light the area up while its service is being started up... Which should make finding out what signal is being sent easier.

**Comment by rsm-gh** [comment]
@Soulsuke another user just described [how to sniff](https://github.com/rsm-gh/akbl/issues/74#issuecomment-658242684), it may help you. Then, if you want to sniff for that specific problem it may be a head ache since the command seems to be launched at boot....

are you able to boot whit the lights off, and then turn them on with the CC? that may be worth to sniff

**Comment by Soulsuke** [comment]
@rsm-gh thabks, I'll give it a try this evening! 

My guess is the CC turns on the lights when its service gets startee by windows, so I hope it wil be possible to disable it at boot, then to manually start it to catch whatever it is sending... We'll see!

**Comment by Soulsuke** [comment]
@rsm-gh I'm at loss for words. I've tried to replicate the issue again but the touchpad backlight isn't showing anymore issues. I've even tried to change the bios settings and to turn the lights off from Windows... Yet now akbl is able to turn the touchpad on as long as the bios setting for "touchpad backlight" is set to "on". 

I'll keep the issue monitored to see if it'll start happening again, the only thing which has changed between my posts has been a system upgrade to kernel 5.7.8...

**Comment by Soulsuke** [comment]
@rsm-gh the issue finally reappeared! I've tried to do some USB sniffing using VMs, but neither via VBox, VMWare nor KVM/QEMU I can get the Alienware Control Center to switch on the touchpad, as the ACC would crash with an error about being unable to contact the component.

Could this be related to the way the device gets recognized under Linux? Is there anything I can do to provide any extra info?

**Comment by rsm-gh** [comment]
Hello @Soulsuke , 

I'm sorry but for the moment I can not help you, maybe in the future after I made a review of the controller and the USB communication. I have too many projects in this moment and too much work so probably it won't be any time soon :/

Kind regards~
