### ISSUE TITLE
Daemon is off [AW m15]

### ISSUE THREAD

**Issue by pulver22** [rsm-gh/akbl#79]
# System information

+ Distribution name: Pop Os 
+ Distribution version: 18.04
+ Python3 version: 3.6.9
+ akbl version: 2019.05.26
+ Computer model: AW m15
+ Daemon status: `off

# Bug description

When querying systemctl I get

```
pulver@pop-os:~$ systemctl status akbl
● akbl.service - AKBL Daemon
   Loaded: loaded (/usr/lib/systemd/system/akbl.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2020-03-11 18:35:54 GMT; 23min ago
 Main PID: 1199 (akbl)
    Tasks: 7 (limit: 4915)
   CGroup: /system.slice/akbl.service
           ├─1199 /bin/bash /usr/bin/akbl --start-daemon
           └─1213 python3 /usr/share/AKBL/launch/daemon.py --start-daemon

Mar 11 18:35:54 pop-os systemd[1]: Started AKBL Daemon.
```

but when I do `akbl --daemon-is-on` I obtain the following: 
```
ERROR from `/usr/lib/python3.6/AKBL/Bindings.py` on method `reload_address`:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/Pyro4/core.py", line 518, in __pyroCreateConnection
    sslContext=sslContext)
  File "/usr/lib/python3/dist-packages/Pyro4/socketutil.py", line 307, in createSocket
    sock.connect(connect)
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.6/AKBL/Bindings.py", line 93, in reload_address
    pyro.ping()
  File "/usr/lib/python3/dist-packages/Pyro4/core.py", line 273, in __getattr__
    self._pyroGetMetadata()
  File "/usr/lib/python3/dist-packages/Pyro4/core.py", line 600, in _pyroGetMetadata
    self.__pyroCreateConnection()
  File "/usr/lib/python3/dist-packages/Pyro4/core.py", line 552, in __pyroCreateConnection
    raise ce
Pyro4.errors.CommunicationError: cannot connect to ('localhost', 44157): [Errno 111] Connection refused


False
```

which prevents me to use the software.

**Comment by pulver22** [comment]
I close the issue because after a reboot the daemon is correctly on. I will open a new ticket because I'm still not able to control the lights.
